interface blurbFormat {
    [key: string]: JSX.Element | string
}

export function getBlurbs() {

    return {
        "coding": <>I specialize in Python and full stack web development. I like these two forms of code because Python lets me experiment with AI and future-facing code, and the web is a form of communnication, and I beleive sharing stories about things you create are almost as important as what they do. I currently work remotely as a full-stack developer at <a href="https://swellai.com" target="blank" className="text-blue-500 shadow cursor-default">SwellAI</a>. A big interest for me has been AI. I am the lead programmer for my robotics team, and my AI autonomous code for our robot won an award at a major robotics tournament. I also trained two programmers from no experience to programming a full robot on their own.</>,
        "editing": "I'm a logical thinker, but I like using my right brain as well. Video editing and visual effects marry logical problem solving and creativity in a way I really like. I've been making videos for YouTube since I was 9 years old, and almost immediately started experimenting with trick videos containing jump cuts, stop motion, and in-camera effects, using the free iPad apps that were available to me. Nowdays, I still love video editing, and have been working with a range of types of effects like CGI, VFX, Deepfakes, 3D motion tracking, and more.",
        "school": "GPA: 3.9+ Unweighted, Second place Individual in the Central Oregon Math Contest written test (Pre-calculus section), National Merit Scholarship qualifying PSAT score (1460), President's Education Award recipient, Cascades Academy Robotics team lead programmer. While I've had more deticated interests outside of school since I was very young, I try to keep up a good academic standing. I exel in subjects that interest me, as has been recognized by my teachers many times.",
        "about": "I was born in Australia in 2006, and, when I was 5 years old, moved to O'ahu, Hawai'i. I then moved to Oregon after a decade in Hawai'i. I attend a rural school called Cascades Academy in Bend, Oregon. I am the lead programmer for our robotics team, and absolutely love it. I also participated in track, doing sprinting and hurdles. I love rock climbing at Bend Rock Gym, and I ski way faster than I should, which far too often leads to injury. My biggest strengths are my intense concentration and my capacity to learn. Click this bubble so I can write more words, I'm almost out of space!",
    } as blurbFormat;
}